### ISSUE TITLE
Decrease binary size please

### ISSUE THREAD

**Issue by SturgeonInc** [oberblastmeister/trash-cli#127]
More of an aesthetic thing rather than a practical one. I just feel that the binary should be smaller than 5Mb for what it is

**Comment by acuteaangle** [comment]
How much smaller do you want the binary to be?
It’s certainly _possible_ to get it smaller, but it’s not necessarily worth the tradeoffs.

`cargo build --release` of 7c48827e55bc results in a 4.7M binary for me.

adding 
```toml
[profile.release]
opt-level = "s"
```
to Cargo.toml brings the binary down to 4.5M, at the cost of efficiency optimizations.

```toml
[profile.release]
opt-level = "s"
strip = true
```
results in 3.4M.

```toml
[profile.release]
opt-level = "s"
strip = true
lto = true
```
results 2.7M.

```toml
[profile.release]
strip = true
lto = true
```

gets us efficiency optimizations back, and still results in a 3.3M binary. That’s likely as small as you can get it without investing significant time into shrinking the binary or incurring performance penalties.
